package main.newsmap.web;

import main.newsmap.web.dto.HotspotDTO;
import main.newsmap.web.dto.HotspotDTO.ArticleDTO;
import org.springframework.web.bind.annotation.*;

import java.util.List;

/**
 * REST controller for hotspot data.
 * Currently returns the same hardcoded hotspots from GlobePane.java.
 * Will later be backed by real clustered news data.
 */
@RestController
@RequestMapping("/api/hotspots")
@CrossOrigin(origins = "*")
public class HotspotController {

    @GetMapping
    public List<HotspotDTO> getHotspots(@RequestParam(name = "category", required = false) String category) {
        List<HotspotDTO> all = buildHotspots();

        if (category != null && !category.isBlank()) {
            return all.stream()
                    .filter(h -> h.category().equalsIgnoreCase(category))
                    .toList();
        }
        return all;
    }

    /**
     * Retrieves actual clustered hotspots generated by the Python embeddings service.
     */
    private List<HotspotDTO> buildHotspots() {
        return analysis.ClusterInspector.generateHotspots();
    }
}
