package main.newsmap.web.dto;

import java.util.List;
import java.util.Map;

/** API projection generated by the persistent event matching engine. */
public record EventFeedDTO(
        String generatedAt,
        String locationGeneratedAt,
        String engineVersion,
        List<EventDTO> events
) {
    public record EventDTO(
            String id,
            String title,
            String status,
            String createdAt,
            String updatedAt,
            String firstPublishedAt,
            String lastPublishedAt,
            int articleCount,
            double confidence,
            Double lat,
            Double lon,
            String location,
            Double locationConfidence,
            String locationMethod,
            String category,
            List<String> sources,
            List<String> entities,
            List<EventUpdateDTO> updates,
            List<EventArticleDTO> articles
    ) {}

    public record EventUpdateDTO(
            String updateId,
            String type,
            String createdAt,
            String articleId,
            String summary,
            Map<String, Object> metadata
    ) {}

    public record EventArticleDTO(
            String articleId,
            String title,
            String source,
            String url,
            String publishTime,
            double matchScore,
            Map<String, Double> matchSignals
    ) {}
}
